USE [master]
GO

/****** Object:  Database [DESAFIO21DIASEFMVC]    Script Date: 20/10/2023 20:57:48 ******/
CREATE DATABASE [DESAFIO21DIASEFMVC] ON  PRIMARY 
( NAME = N'DESAFIO21DIASEFMVC', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\DESAFIO21DIASEFMVC.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DESAFIO21DIASEFMVC_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\DESAFIO21DIASEFMVC_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DESAFIO21DIASEFMVC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET ARITHABORT OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET  MULTI_USER 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DESAFIO21DIASEFMVC] SET  READ_WRITE 
GO

